// This file was auto-generated by Fern from our API Definition.

/**
 * List of attributes
 */
export interface GetCrmAttributesDealsResponseItem {
    attributeOptions?: Record<string, unknown>[];
    attributeTypeName?: string;
    internalName?: string;
    isRequired?: boolean;
    label?: string;
}
