// This file was auto-generated by Fern from our API Definition.

/**
 * List of attributes
 */
export interface GetCrmAttributesDealsResponseItem {
    attributeOptions?: Record<string, unknown>[] | undefined;
    attributeTypeName?: string | undefined;
    internalName?: string | undefined;
    isRequired?: boolean | undefined;
    label?: string | undefined;
}
