// This file was auto-generated by Fern from our API Definition.

export const GetCrmDealsRequestSort = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type GetCrmDealsRequestSort = (typeof GetCrmDealsRequestSort)[keyof typeof GetCrmDealsRequestSort];
