/**
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetCouponCollection {
    /**
    * The id of the collection.
    */
    'id': string;
    /**
    * The name of the collection.
    */
    'name': string;
    /**
    * The default coupon of the collection.
    */
    'defaultCoupon': string;
    /**
    * Datetime on which the collection was created.
    */
    'createdAt': Date;
    /**
    * Total number of coupons in the collection.
    */
    'totalCoupons': number;
    /**
    * Number of coupons that have not been sent yet.
    */
    'remainingCoupons': number;
    /**
    * Expiration date for the coupon collection in RFC3339 format.
    */
    'expirationDate'?: Date;
    /**
    * If present, an email notification is going to be sent the defined amount of days before the expiration date.
    */
    'remainingDaysAlert'?: number;
    /**
    * If present, an email notification is going to be sent when the total number of available coupons falls below the defined threshold.
    */
    'remainingCouponsAlert'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "defaultCoupon",
            "baseName": "defaultCoupon",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "totalCoupons",
            "baseName": "totalCoupons",
            "type": "number"
        },
        {
            "name": "remainingCoupons",
            "baseName": "remainingCoupons",
            "type": "number"
        },
        {
            "name": "expirationDate",
            "baseName": "expirationDate",
            "type": "Date"
        },
        {
            "name": "remainingDaysAlert",
            "baseName": "remainingDaysAlert",
            "type": "number"
        },
        {
            "name": "remainingCouponsAlert",
            "baseName": "remainingCouponsAlert",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetCouponCollection.attributeTypeMap;
    }
}

