/**
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MainRedeem {
    /**
    * Timestamp when the redemption was cancelled
    */
    'cancelledAt'?: Date;
    /**
    * Timestamp when the redemption was completed
    */
    'completedAt'?: Date;
    /**
    * Unique identifier for the contact
    */
    'contactId'?: number;
    /**
    * Timestamp when the redemption was created
    */
    'createdAt'?: Date;
    /**
    * Unique identifier for the debit transaction
    */
    'debitTransactionId'?: string;
    /**
    * Timestamp when the redemption expires
    */
    'expiresAt'?: Date;
    /**
    * Unique identifier for the redemption
    */
    'id'?: string;
    /**
    * Unique identifier for the loyalty program
    */
    'loyaltyProgramId'?: string;
    /**
    * Additional metadata associated with the redemption
    */
    'meta'?: { [key: string]: any; };
    /**
    * Reason for rejection if the redemption was rejected
    */
    'rejectReason'?: string;
    /**
    * Timestamp when the redemption was rejected
    */
    'rejectedAt'?: Date;
    /**
    * Unique identifier for the reward attribution
    */
    'rewardAttributionId'?: string;
    /**
    * Current status of the redemption
    */
    'status'?: string;
    /**
    * Timestamp when the redemption was last updated
    */
    'updatedAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancelledAt",
            "baseName": "cancelledAt",
            "type": "Date"
        },
        {
            "name": "completedAt",
            "baseName": "completedAt",
            "type": "Date"
        },
        {
            "name": "contactId",
            "baseName": "contactId",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "debitTransactionId",
            "baseName": "debitTransactionId",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "loyaltyProgramId",
            "baseName": "loyaltyProgramId",
            "type": "string"
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "rejectReason",
            "baseName": "rejectReason",
            "type": "string"
        },
        {
            "name": "rejectedAt",
            "baseName": "rejectedAt",
            "type": "Date"
        },
        {
            "name": "rewardAttributionId",
            "baseName": "rewardAttributionId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return MainRedeem.attributeTypeMap;
    }
}

