// This file was auto-generated by Fern from our API Definition.

import type * as Brevo from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetSmsEventsRequest {
    /** Number of documents per page */
    limit?: number;
    /** **Mandatory if endDate is used.** Starting date (YYYY-MM-DD) of the report */
    startDate?: string;
    /** **Mandatory if startDate is used.** Ending date (YYYY-MM-DD) of the report */
    endDate?: string;
    /** Index of the first document of the page */
    offset?: number;
    /** Number of days in the past including today (positive integer). **Not compatible with 'startDate' and 'endDate'** */
    days?: number;
    /** Filter the report for a specific phone number */
    phoneNumber?: string;
    /** Filter the report for specific events */
    event?: Brevo.GetSmsEventsRequestEvent;
    /** Filter the report for specific tags passed as a serialized urlencoded array */
    tags?: string;
    /** Sort the results in the ascending/descending order of record creation. Default order is **descending** if `sort` is not passed */
    sort?: Brevo.GetSmsEventsRequestSort;
}
