// This file was auto-generated by Fern from our API Definition.

export interface SubscribeMemberToASubscriptionResponse {
    /** Timestamp when the subscription member was created. */
    createdAt?: string;
    /** List of unique member contact IDs. */
    memberContactIds?: number[];
    /** Unique identifier of the organization. */
    organizationId?: number;
    /** Unique identifier of the subscription owner. */
    ownerContactId?: number;
    /** Timestamp when the subscription member was last updated. */
    updatedAt?: string;
}
