// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Brevo from "../../../index.js";

export declare namespace ProcessClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ProcessClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ProcessClient.Options>;

    constructor(options: ProcessClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieves a list of background processes from your Brevo account with filtering and pagination.
     *
     * **Use this to:**
     * - Monitor background process activity and status
     * - Track long-running operations and tasks
     * - Find process IDs for detailed status checking
     * - Review process history and performance
     * - Identify failed or stuck processes for troubleshooting
     *
     * **Key information returned:**
     * - Process details (ID, name, status)
     * - Export download URLs for completed export processes
     * - Import details with CSV report URLs for completed import processes
     * - Total count of processes for pagination
     *
     * **Important considerations:**
     * - Background processes handle long-running operations like imports and exports
     * - Process status indicates current state (queued, processing, completed)
     * - Export processes provide download URLs when completed
     * - Import processes provide CSV report URLs with details about problematic records
     * - Use pagination for accounts with many historical processes
     * - Sort options available for creation order (ascending or descending)
     * - Default limit is 10 results per page, maximum is 50
     *
     * @param {Brevo.GetProcessesRequest} request
     * @param {ProcessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     * @throws {@link errors.BrevoError}
     * @throws {@link errors.BrevoTimeoutError}
     *
     * @example
     *     await client.process.getProcesses()
     */
    public getProcesses(
        request: Brevo.GetProcessesRequest = {},
        requestOptions?: ProcessClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.GetProcessesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getProcesses(request, requestOptions));
    }

    private async __getProcesses(
        request: Brevo.GetProcessesRequest = {},
        requestOptions?: ProcessClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.GetProcessesResponse>> {
        const { limit, offset, sort } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            sort: sort != null ? sort : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                "processes",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.GetProcessesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/processes");
    }

    /**
     * Retrieves detailed information about a specific background process.
     *
     * **Use this to:**
     * - Get detailed status of a specific process
     * - Monitor process progress and completion
     * - Download results from completed export processes
     * - Check error details for failed processes
     * - Track process execution times
     *
     * **Key information returned:**
     * - Complete process details (ID, name, status)
     * - Download URLs for completed export processes
     * - Import details with CSV report URLs for completed import processes
     *
     * **Important considerations:**
     * - Process ID must exist in your account and not be deleted
     * - Completed export processes include download URLs
     * - Completed import processes include CSV report URLs with details about problematic records
     * - Different process types return different result structures
     *
     * @param {Brevo.GetProcessRequest} request
     * @param {ProcessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     * @throws {@link Brevo.NotFoundError}
     * @throws {@link errors.BrevoError}
     * @throws {@link errors.BrevoTimeoutError}
     *
     * @example
     *     await client.process.getProcess({
     *         processId: 1000000
     *     })
     */
    public getProcess(
        request: Brevo.GetProcessRequest,
        requestOptions?: ProcessClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.GetProcessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getProcess(request, requestOptions));
    }

    private async __getProcess(
        request: Brevo.GetProcessRequest,
        requestOptions?: ProcessClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.GetProcessResponse>> {
        const { processId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `processes/${core.url.encodePathParam(processId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.GetProcessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/processes/{processId}");
    }
}
