// This file was auto-generated by Fern from our API Definition.

import type * as Brevo from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetProductsRequest {
    /** Number of documents per page */
    limit?: number;
    /** Index of the first document in the page */
    offset?: number;
    /** Sort the results in the ascending/descending order of record creation. Default order is **descending** if `sort` is not passed */
    sort?: Brevo.GetProductsRequestSort;
    /** Filter by product ids */
    ids?: string | string[];
    /** Filter by product name, minimum 3 characters should be present for search. */
    name?: string;
    /** Price filter for products less than and equals to particular amount */
    "price[lte]"?: number;
    /** Price filter for products greater than and equals to particular amount */
    "price[gte]"?: number;
    /** Price filter for products less than particular amount */
    "price[lt]"?: number;
    /** Price filter for products greater than particular amount */
    "price[gt]"?: number;
    /** Price filter for products equals to particular amount */
    "price[eq]"?: number;
    /** Price filter for products not equals to particular amount */
    "price[ne]"?: number;
    /** Filter by categories ids */
    categories?: string | string[];
    /** Filter (urlencoded) the orders modified after a given UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ). **Prefer to pass your timezone in date-time format for accurate result.** */
    modifiedSince?: string;
    /** Filter (urlencoded) the orders created after a given UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ). **Prefer to pass your timezone in date-time format for accurate result.** */
    createdSince?: string;
    /** Filter products by their deletion status. If `false` is passed, only products that are not deleted will be returned. */
    isDeleted?: string;
}
