// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface DeleteHardbouncesRequest {
    /** Target a specific email address */
    contactEmail?: string;
    /** Ending date (YYYY-MM-DD) of the time period for deletion. The hardbounces until this date will be deleted. Must be greater than or equal to the startDate */
    endDate?: string;
    /** Starting date (YYYY-MM-DD) of the time period for deletion. The hardbounces occurred after this date will be deleted. Must be less than or equal to the endDate */
    startDate?: string;
}
