// This file was auto-generated by Fern from our API Definition.

import type * as Brevo from "../../../../index.js";

/**
 * @example
 *     {
 *         templateId: 1000000
 *     }
 */
export interface GetSmtpTemplateRequest {
    /** ID of the template. Can be a numeric template ID or a custom template identifier string (alphanumeric, hyphens, and underscores only, max 64 characters, must start with a letter). */
    templateId: Brevo.GetSmtpTemplateRequestTemplateId;
}
