// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetCorporateInvitedUsersListRequest {
    /**
     * User type (active | pending). This is required if offset is provided for
     * limited result.
     */
    type?: string;
    /**
     * Page number for the result set. This is optional, default value will be
     * the 1st page.
     */
    offset?: number;
    /**
     * Number of users to be displayed on each page. This is optional, the
     * default limit is 20, but max allowed limit is 100.
     */
    limit?: number;
}
