// This file was auto-generated by Fern from our API Definition.

import type * as Brevo from "../../../index.js";

export interface GetWhatsAppCampaignsResponse {
    campaigns?: GetWhatsAppCampaignsResponse.Campaigns.Item[] | undefined;
    /** Number of WhatsApp campaigns retrieved */
    count?: number | undefined;
}

export namespace GetWhatsAppCampaignsResponse {
    export type Campaigns = Campaigns.Item[];

    export namespace Campaigns {
        export interface Item {
            /** Name of the WhatsApp Campaign */
            campaignName: string;
            /** Status of the Whatsapp Campaign */
            campaignStatus: Item.CampaignStatus;
            /** Creation UTC date-time of the WhatsApp campaign (YYYY-MM-DDTHH:mm:ss.SSSZ) */
            createdAt: string;
            /** Error Reason associated with the WhatsApp campaign sending */
            errorReason?: string | undefined;
            /** ID of the WhatsApp Campaign */
            id: number;
            /** Count of invalidated contacts */
            invalidatedContacts?: number | undefined;
            /** UTC date-time of last modification of the WhatsApp campaign (YYYY-MM-DDTHH:mm:ss.SSSZ) */
            modifiedAt: string;
            /** Read percentage of the the whatsapp campaign created */
            readPercentage?: number | undefined;
            /** UTC date-time on which WhatsApp campaign is scheduled. Should be in YYYY-MM-DDTHH:mm:ss.SSSZ format */
            scheduledAt: string;
            stats?: Brevo.WhatsappCampStats | undefined;
            /** Id of the WhatsApp template */
            templateId: string;
        }

        export namespace Item {
            /** Status of the Whatsapp Campaign */
            export const CampaignStatus = {
                Draft: "draft",
                Scheduled: "scheduled",
                Pending: "pending",
                Approved: "approved",
                Running: "running",
                Suspended: "suspended",
                Rejected: "rejected",
                Sent: "sent",
            } as const;
            export type CampaignStatus = (typeof CampaignStatus)[keyof typeof CampaignStatus];
        }
    }
}
