// This file was auto-generated by Fern from our API Definition.

import type * as Brevo from "../../../../index.js";

/**
 * @example
 *     {
 *         pid: "pid"
 *     }
 */
export interface GetLoyaltyOfferProgramsPidOffersRequest {
    /** Loyalty Program ID */
    pid: string;
    /** Page size */
    limit?: number;
    /** Pagination offset */
    offset?: number;
    /** State of the reward */
    state?: string;
    /** Version */
    version?: Brevo.GetLoyaltyOfferProgramsPidOffersRequestVersion;
}
