// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "support@example.com",
 *         name: "Support Team"
 *     }
 *
 * @example
 *     {
 *         email: "marketing@example.com",
 *         ips: [{
 *                 domain: "example.com",
 *                 ip: "203.0.113.100",
 *                 weight: 100
 *             }],
 *         name: "Marketing Team"
 *     }
 *
 * @example
 *     {
 *         email: "newsletter@example.com",
 *         ips: [{
 *                 domain: "example.com",
 *                 ip: "203.0.113.100",
 *                 weight: 60
 *             }, {
 *                 domain: "news.example.com",
 *                 ip: "203.0.113.101",
 *                 weight: 40
 *             }],
 *         name: "Newsletter"
 *     }
 *
 * @example
 *     {
 *         email: "support@example.com",
 *         name: "Support Team"
 *     }
 *
 * @example
 *     {
 *         email: "support@example.com",
 *         name: "Support Team"
 *     }
 */
export interface CreateSenderRequest {
    /**
     * From email to use for the sender. A verification email will be
     * sent to this address.
     */
    email: string;
    /**
     * **Mandatory in case of dedicated IP**. IPs to associate to the
     * sender. Not required for standard accounts.
     */
    ips?: CreateSenderRequest.Ips.Item[];
    /** From Name to use for the sender */
    name: string;
}

export namespace CreateSenderRequest {
    export type Ips = Ips.Item[];

    export namespace Ips {
        export interface Item {
            /** Domain of the IP */
            domain: string;
            /** Dedicated IP available in your account */
            ip: string;
            /**
             * Weight to apply to the IP. Sum of all IP weights must be
             * 100. Should be passed for either ALL or NONE of the IPs.
             * If it's not passed, the sending will be equally balanced
             * on all IPs.
             */
            weight?: number | undefined;
        }
    }
}
