// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         senderId: 1000000,
 *         name: "New Support Team"
 *     }
 *
 * @example
 *     {
 *         senderId: 1000000,
 *         email: "newsupport@mycompany.com"
 *     }
 *
 * @example
 *     {
 *         senderId: 1000000,
 *         email: "marketing@mycompany.com",
 *         name: "Marketing Team"
 *     }
 *
 * @example
 *     {
 *         senderId: 1000000,
 *         email: "marketing@enterprise.com",
 *         ips: [{
 *                 domain: "enterprise.com",
 *                 ip: "192.168.1.100",
 *                 weight: 100
 *             }],
 *         name: "Enterprise Marketing"
 *     }
 *
 * @example
 *     {
 *         senderId: 1000000,
 *         email: "campaigns@enterprise.com",
 *         ips: [{
 *                 domain: "enterprise.com",
 *                 ip: "192.168.1.100",
 *                 weight: 70
 *             }, {
 *                 domain: "mail.enterprise.com",
 *                 ip: "192.168.1.101",
 *                 weight: 30
 *             }],
 *         name: "Multi-IP Sender"
 *     }
 */
export interface UpdateSenderRequest {
    /** Id of the sender */
    senderId: number;
    /** From Email to update the sender */
    email?: string;
    /**
     * **Only in case of dedicated IP**. IPs to associate to the
     * sender. If passed, will replace all the existing IPs. Not required for standard accounts.
     */
    ips?: UpdateSenderRequest.Ips.Item[];
    /** From Name to update the sender */
    name?: string;
}

export namespace UpdateSenderRequest {
    export type Ips = Ips.Item[];

    export namespace Ips {
        export interface Item {
            /** Domain of the IP */
            domain: string;
            /** Dedicated IP available in your account */
            ip: string;
            /**
             * Weight to apply to the IP. Sum of all IP weights must be
             * 100. Should be passed for either ALL or NONE of the IPs.
             * If it's not passed, the sending will be equally balanced
             * on all IPs.
             */
            weight?: number | undefined;
        }
    }
}
