// This file was auto-generated by Fern from our API Definition.

export interface GetCorporateIpResponseItem {
    domain?: string | undefined;
    ip?: string | undefined;
    transactional?: boolean | undefined;
}
