// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         campaignId: 1000000
 *     }
 */
export interface UpdateWhatsAppCampaignRequest {
    /** id of the campaign */
    campaignId: number;
    /** Name of the campaign */
    campaignName?: string;
    /** Status of the campaign */
    campaignStatus?: UpdateWhatsAppCampaignRequest.CampaignStatus;
    /** Segment ids and List ids to include/exclude from campaign */
    recipients?: UpdateWhatsAppCampaignRequest.Recipients;
    /** Reschedule the sending UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) of campaign. **Prefer to pass your timezone in date-time format for accurate result.For example: **2017-06-01T12:30:00+02:00** Use this field to update the scheduledAt of any existing draft or scheduled WhatsApp campaign. */
    rescheduleFor?: string;
}

export namespace UpdateWhatsAppCampaignRequest {
    /** Status of the campaign */
    export const CampaignStatus = {
        Scheduled: "scheduled",
        Suspended: "suspended",
    } as const;
    export type CampaignStatus = (typeof CampaignStatus)[keyof typeof CampaignStatus];

    /**
     * Segment ids and List ids to include/exclude from campaign
     */
    export interface Recipients {
        /** List ids to exclude from the campaign */
        excludedListIds?: number[] | undefined;
        /** **Mandatory if scheduledAt is not empty**. List Ids to send the campaign to */
        listIds?: number[] | undefined;
        /** **Mandatory if listIds are not used**. Segment ids to send the campaign to. */
        segments?: number[] | undefined;
    }
}
