// This file was auto-generated by Fern from our API Definition.

export const GetCrmFilesRequestEntity = {
    Companies: "companies",
    Deals: "deals",
    Contacts: "contacts",
} as const;
export type GetCrmFilesRequestEntity = (typeof GetCrmFilesRequestEntity)[keyof typeof GetCrmFilesRequestEntity];
