// This file was auto-generated by Fern from our API Definition.

export interface BalanceLimit {
    /** balance definition ID */
    balanceDefinitionId?: string;
    /** Defines the type of constraint (e.g., transaction-based or amount-based). */
    constraintType?: string;
    /** Timestamp of when the balance limit was created. */
    createdAt: string;
    /** Time unit for the balance limit (day, week, month, year). */
    durationUnit?: string;
    /** Number of time units the balance limit applies to. */
    durationValue?: number;
    /** Unique identifier for the balance limit. */
    id?: string;
    /** Indicates if the limit resets periodically based on a sliding schedule. */
    slidingSchedule?: boolean;
    /** Specifies whether the limit applies to credit or debit transactions. */
    transactionType?: string;
    /** Timestamp of the last update to the balance limit. */
    updatedAt: string;
    /** The maximum allowed value for the defined constraint. */
    value?: number;
}
