// This file was auto-generated by Fern from our API Definition.

/**
 * A contact's membership status in a single consent group.
 */
export interface ConsentGroupItem {
    /** ID of the consent group */
    id: number;
    /** The contact's subscription status within this consent group */
    status: ConsentGroupItem.Status;
}

export namespace ConsentGroupItem {
    /** The contact's subscription status within this consent group */
    export const Status = {
        Subscribed: "subscribed",
        Unsubscribed: "unsubscribed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
