// This file was auto-generated by Fern from our API Definition.

/**
 * A consent group representing a category of contact opt-in/opt-out preferences.
 */
export interface ConsentGroup {
    /** Unique identifier for the consent group */
    id: number;
    /** Display name of the consent group */
    name: string;
    /** Optional description of the consent group */
    description?: string | undefined;
    /** Controls how contacts are added to the group. `manual` — contacts are added explicitly via the API. `automatic` — contacts are added automatically at signup. */
    signupMode: ConsentGroup.SignupMode;
    /** Number of contacts currently in this consent group */
    contactsCount: number;
    /** Whether this is a system-created default consent group */
    isDefault: boolean;
    /** UTC date-time when the consent group was created (YYYY-MM-DDTHH:mm:ss.SSSZ) */
    createdAt: string;
    /** UTC date-time when the consent group was last updated (YYYY-MM-DDTHH:mm:ss.SSSZ) */
    updatedAt: string;
}

export namespace ConsentGroup {
    /** Controls how contacts are added to the group. `manual` — contacts are added explicitly via the API. `automatic` — contacts are added automatically at signup. */
    export const SignupMode = {
        Manual: "manual",
        Automatic: "automatic",
    } as const;
    export type SignupMode = (typeof SignupMode)[keyof typeof SignupMode];
}
