// This file was auto-generated by Fern from our API Definition.

/**
 * Deal Details
 */
export interface Deal {
    /** Unique deal id */
    id?: string | undefined;
    /** Deal attributes with values */
    attributes?: Record<string, unknown> | undefined;
    /** Contact ids for contacts linked to this deal */
    linkedContactsIds?: number[] | undefined;
    /** Companies ids for companies linked to this deal */
    linkedCompaniesIds?: string[] | undefined;
}
