// This file was auto-generated by Fern from our API Definition.

export interface GetCampaignRecipients {
    /** Segment IDs excluded from the campaign */
    excludedSegments?: number[] | undefined;
    exclusionLists: number[];
    lists: number[];
    /** Segment IDs included in the campaign */
    segments?: number[] | undefined;
}
