// This file was auto-generated by Fern from our API Definition.

export const GetScheduledEmailByIdRequestStatus = {
    Processed: "processed",
    InProgress: "inProgress",
    Queued: "queued",
} as const;
export type GetScheduledEmailByIdRequestStatus =
    (typeof GetScheduledEmailByIdRequestStatus)[keyof typeof GetScheduledEmailByIdRequestStatus];
