// This file was auto-generated by Fern from our API Definition.

export const GetTransacBlockedContactsRequestSort = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type GetTransacBlockedContactsRequestSort =
    (typeof GetTransacBlockedContactsRequestSort)[keyof typeof GetTransacBlockedContactsRequestSort];
