// This file was auto-generated by Fern from our API Definition.

export interface PostPreviewSmtpEmailTemplatesResponse {
    /** Sender email address */
    fromEmail?: string;
    /** Sender Name */
    fromName?: string;
    /** Html content of the template */
    html?: string;
    /** Preview text of the template */
    previewText?: string;
    /** subject of the template */
    subject?: string;
    usedFeedNames?: string[];
}
