// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Brevo from "../../../index.js";

export declare namespace TierClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TierClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TierClient.Options>;

    constructor(options: TierClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Manually assigns a tier to a specific membership.
     *
     * @param {Brevo.AddSubscriptionToTierRequest} request
     * @param {TierClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.UnauthorizedError}
     * @throws {@link Brevo.ForbiddenError}
     * @throws {@link Brevo.NotFoundError}
     * @throws {@link Brevo.ConflictError}
     * @throws {@link Brevo.UnprocessableEntityError}
     * @throws {@link Brevo.FailedDependencyError}
     * @throws {@link Brevo.InternalServerError}
     *
     * @example
     *     await client.tier.addSubscriptionToTier({
     *         pid: "pid",
     *         cid: "cid",
     *         tid: "tid"
     *     })
     */
    public addSubscriptionToTier(
        request: Brevo.AddSubscriptionToTierRequest,
        requestOptions?: TierClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.AddSubscriptionToTierResponse> {
        return core.HttpResponsePromise.fromPromise(this.__addSubscriptionToTier(request, requestOptions));
    }

    private async __addSubscriptionToTier(
        request: Brevo.AddSubscriptionToTierRequest,
        requestOptions?: TierClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.AddSubscriptionToTierResponse>> {
        const { pid, cid, tid } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `loyalty/tier/programs/${core.url.encodePathParam(pid)}/contacts/${core.url.encodePathParam(cid)}/tiers/${core.url.encodePathParam(tid)}`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.AddSubscriptionToTierResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Brevo.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Brevo.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new Brevo.ConflictError(_response.error.body as Brevo.ErrorModel, _response.rawResponse);
                case 422:
                    throw new Brevo.UnprocessableEntityError(
                        _response.error.body as Brevo.ErrorModel,
                        _response.rawResponse,
                    );
                case 424:
                    throw new Brevo.FailedDependencyError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Brevo.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/loyalty/tier/programs/{pid}/contacts/{cid}/tiers/{tid}",
        );
    }

    /**
     * Returns the list of tier groups defined within the loyalty program.
     *
     * @param {Brevo.GetListOfTierGroupsRequest} request
     * @param {TierClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.UnauthorizedError}
     * @throws {@link Brevo.ForbiddenError}
     * @throws {@link Brevo.NotFoundError}
     * @throws {@link Brevo.UnprocessableEntityError}
     * @throws {@link Brevo.InternalServerError}
     *
     * @example
     *     await client.tier.getListOfTierGroups({
     *         pid: "pid"
     *     })
     */
    public getListOfTierGroups(
        request: Brevo.GetListOfTierGroupsRequest,
        requestOptions?: TierClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.GetListOfTierGroupsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getListOfTierGroups(request, requestOptions));
    }

    private async __getListOfTierGroups(
        request: Brevo.GetListOfTierGroupsRequest,
        requestOptions?: TierClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.GetListOfTierGroupsResponse>> {
        const { pid, version } = request;
        const _queryParams: Record<string, unknown> = {
            version: version != null ? version : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `loyalty/tier/programs/${core.url.encodePathParam(pid)}/tier-groups`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.GetListOfTierGroupsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Brevo.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Brevo.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Brevo.UnprocessableEntityError(
                        _response.error.body as Brevo.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Brevo.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/loyalty/tier/programs/{pid}/tier-groups",
        );
    }

    /**
     * Creates a new tier group in a loyalty program. *(The changes will take effect with the next publication of the loyalty program)*
     *
     * @param {Brevo.CreateTierGroupRequest} request
     * @param {TierClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     * @throws {@link Brevo.UnauthorizedError}
     * @throws {@link Brevo.ForbiddenError}
     * @throws {@link Brevo.NotFoundError}
     * @throws {@link Brevo.ConflictError}
     * @throws {@link Brevo.UnprocessableEntityError}
     *
     * @example
     *     await client.tier.createTierGroup({
     *         pid: "pid",
     *         name: "name"
     *     })
     */
    public createTierGroup(
        request: Brevo.CreateTierGroupRequest,
        requestOptions?: TierClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.TierGroup> {
        return core.HttpResponsePromise.fromPromise(this.__createTierGroup(request, requestOptions));
    }

    private async __createTierGroup(
        request: Brevo.CreateTierGroupRequest,
        requestOptions?: TierClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.TierGroup>> {
        const { pid, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `loyalty/tier/programs/${core.url.encodePathParam(pid)}/tier-groups`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.TierGroup, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Brevo.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Brevo.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new Brevo.ConflictError(_response.error.body as Brevo.ErrorModel, _response.rawResponse);
                case 422:
                    throw new Brevo.UnprocessableEntityError(
                        _response.error.body as Brevo.ErrorModel,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/loyalty/tier/programs/{pid}/tier-groups",
        );
    }

    /**
     * Returns tier group information.
     *
     * @param {Brevo.GetTierGroupRequest} request
     * @param {TierClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.UnauthorizedError}
     * @throws {@link Brevo.ForbiddenError}
     * @throws {@link Brevo.NotFoundError}
     * @throws {@link Brevo.UnprocessableEntityError}
     * @throws {@link Brevo.InternalServerError}
     *
     * @example
     *     await client.tier.getTierGroup({
     *         pid: "pid",
     *         gid: "gid"
     *     })
     */
    public getTierGroup(
        request: Brevo.GetTierGroupRequest,
        requestOptions?: TierClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.TierGroup> {
        return core.HttpResponsePromise.fromPromise(this.__getTierGroup(request, requestOptions));
    }

    private async __getTierGroup(
        request: Brevo.GetTierGroupRequest,
        requestOptions?: TierClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.TierGroup>> {
        const { pid, gid, version } = request;
        const _queryParams: Record<string, unknown> = {
            version: version != null ? version : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `loyalty/tier/programs/${core.url.encodePathParam(pid)}/tier-groups/${core.url.encodePathParam(gid)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.TierGroup, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Brevo.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Brevo.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Brevo.UnprocessableEntityError(
                        _response.error.body as Brevo.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Brevo.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/loyalty/tier/programs/{pid}/tier-groups/{gid}",
        );
    }

    /**
     * Updates a tier group from a loyalty program. *(The changes will take effect with the next publication of the loyalty program)*
     *
     * @param {Brevo.UpdateTierGroupRequest} request
     * @param {TierClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.UnauthorizedError}
     * @throws {@link Brevo.ForbiddenError}
     * @throws {@link Brevo.NotFoundError}
     * @throws {@link Brevo.UnprocessableEntityError}
     * @throws {@link Brevo.InternalServerError}
     *
     * @example
     *     await client.tier.updateTierGroup({
     *         pid: "pid",
     *         gid: "gid",
     *         downgradeStrategy: "real_time",
     *         name: "name",
     *         tierOrder: ["tierOrder"],
     *         upgradeStrategy: "real_time"
     *     })
     */
    public updateTierGroup(
        request: Brevo.UpdateTierGroupRequest,
        requestOptions?: TierClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.TierGroup> {
        return core.HttpResponsePromise.fromPromise(this.__updateTierGroup(request, requestOptions));
    }

    private async __updateTierGroup(
        request: Brevo.UpdateTierGroupRequest,
        requestOptions?: TierClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.TierGroup>> {
        const { pid, gid, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `loyalty/tier/programs/${core.url.encodePathParam(pid)}/tier-groups/${core.url.encodePathParam(gid)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.TierGroup, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Brevo.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Brevo.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Brevo.UnprocessableEntityError(
                        _response.error.body as Brevo.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Brevo.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/loyalty/tier/programs/{pid}/tier-groups/{gid}",
        );
    }

    /**
     * Deletes a tier group from a loyalty program. *(The changes will take effect with the next publication of the loyalty program)*
     *
     * @param {Brevo.DeleteTierGroupRequest} request
     * @param {TierClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.UnauthorizedError}
     * @throws {@link Brevo.ForbiddenError}
     * @throws {@link Brevo.NotFoundError}
     * @throws {@link Brevo.ConflictError}
     * @throws {@link Brevo.UnprocessableEntityError}
     * @throws {@link Brevo.InternalServerError}
     *
     * @example
     *     await client.tier.deleteTierGroup({
     *         pid: "pid",
     *         gid: "gid"
     *     })
     */
    public deleteTierGroup(
        request: Brevo.DeleteTierGroupRequest,
        requestOptions?: TierClient.RequestOptions,
    ): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__deleteTierGroup(request, requestOptions));
    }

    private async __deleteTierGroup(
        request: Brevo.DeleteTierGroupRequest,
        requestOptions?: TierClient.RequestOptions,
    ): Promise<core.WithRawResponse<string>> {
        const { pid, gid } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `loyalty/tier/programs/${core.url.encodePathParam(pid)}/tier-groups/${core.url.encodePathParam(gid)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Brevo.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Brevo.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new Brevo.ConflictError(_response.error.body as Brevo.ErrorModel, _response.rawResponse);
                case 422:
                    throw new Brevo.UnprocessableEntityError(
                        _response.error.body as Brevo.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Brevo.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/loyalty/tier/programs/{pid}/tier-groups/{gid}",
        );
    }

    /**
     * Creates a new tier in a loyalty program tier group. *(The changes will take effect with the next publication of the loyalty program)*
     *
     * @param {Brevo.CreateTierForTierGroupRequest} request
     * @param {TierClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.UnauthorizedError}
     * @throws {@link Brevo.ForbiddenError}
     * @throws {@link Brevo.NotFoundError}
     * @throws {@link Brevo.UnprocessableEntityError}
     * @throws {@link Brevo.InternalServerError}
     *
     * @example
     *     await client.tier.createTierForTierGroup({
     *         pid: "pid",
     *         gid: "gid",
     *         accessConditions: [{}],
     *         name: "name"
     *     })
     */
    public createTierForTierGroup(
        request: Brevo.CreateTierForTierGroupRequest,
        requestOptions?: TierClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.Tier> {
        return core.HttpResponsePromise.fromPromise(this.__createTierForTierGroup(request, requestOptions));
    }

    private async __createTierForTierGroup(
        request: Brevo.CreateTierForTierGroupRequest,
        requestOptions?: TierClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.Tier>> {
        const { pid, gid, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `loyalty/tier/programs/${core.url.encodePathParam(pid)}/tier-groups/${core.url.encodePathParam(gid)}/tiers`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.Tier, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Brevo.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Brevo.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Brevo.UnprocessableEntityError(
                        _response.error.body as Brevo.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Brevo.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/loyalty/tier/programs/{pid}/tier-groups/{gid}/tiers",
        );
    }

    /**
     * Returns the list of tiers defined within the loyalty program.
     *
     * @param {Brevo.GetLoyaltyProgramTierRequest} request
     * @param {TierClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.UnauthorizedError}
     * @throws {@link Brevo.ForbiddenError}
     * @throws {@link Brevo.NotFoundError}
     * @throws {@link Brevo.UnprocessableEntityError}
     * @throws {@link Brevo.InternalServerError}
     *
     * @example
     *     await client.tier.getLoyaltyProgramTier({
     *         pid: "pid"
     *     })
     */
    public getLoyaltyProgramTier(
        request: Brevo.GetLoyaltyProgramTierRequest,
        requestOptions?: TierClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.GetLoyaltyProgramTierResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getLoyaltyProgramTier(request, requestOptions));
    }

    private async __getLoyaltyProgramTier(
        request: Brevo.GetLoyaltyProgramTierRequest,
        requestOptions?: TierClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.GetLoyaltyProgramTierResponse>> {
        const { pid, version } = request;
        const _queryParams: Record<string, unknown> = {
            version: version != null ? version : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `loyalty/tier/programs/${core.url.encodePathParam(pid)}/tiers`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.GetLoyaltyProgramTierResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Brevo.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Brevo.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Brevo.UnprocessableEntityError(
                        _response.error.body as Brevo.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Brevo.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/loyalty/tier/programs/{pid}/tiers",
        );
    }

    /**
     * Modifies an existing tier for the specified tier group *(The changes will take effect with the next publication of the loyalty program)*
     *
     * @param {Brevo.UpdateTierRequest} request
     * @param {TierClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.UnauthorizedError}
     * @throws {@link Brevo.ForbiddenError}
     * @throws {@link Brevo.NotFoundError}
     * @throws {@link Brevo.UnprocessableEntityError}
     * @throws {@link Brevo.InternalServerError}
     *
     * @example
     *     await client.tier.updateTier({
     *         pid: "pid",
     *         tid: "tid",
     *         accessConditions: [{}],
     *         name: "name",
     *         tierRewards: [{}]
     *     })
     */
    public updateTier(
        request: Brevo.UpdateTierRequest,
        requestOptions?: TierClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.Tier> {
        return core.HttpResponsePromise.fromPromise(this.__updateTier(request, requestOptions));
    }

    private async __updateTier(
        request: Brevo.UpdateTierRequest,
        requestOptions?: TierClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.Tier>> {
        const { pid, tid, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `loyalty/tier/programs/${core.url.encodePathParam(pid)}/tiers/${core.url.encodePathParam(tid)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.Tier, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Brevo.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Brevo.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Brevo.UnprocessableEntityError(
                        _response.error.body as Brevo.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Brevo.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/loyalty/tier/programs/{pid}/tiers/{tid}",
        );
    }

    /**
     * Deletes a tier from a loyalty program tier group. *(The changes will take effect with the next publication of the loyalty program)*
     *
     * @param {Brevo.DeleteTierRequest} request
     * @param {TierClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.UnauthorizedError}
     * @throws {@link Brevo.ForbiddenError}
     * @throws {@link Brevo.NotFoundError}
     * @throws {@link Brevo.UnprocessableEntityError}
     * @throws {@link Brevo.InternalServerError}
     *
     * @example
     *     await client.tier.deleteTier({
     *         pid: "pid",
     *         tid: "tid"
     *     })
     */
    public deleteTier(
        request: Brevo.DeleteTierRequest,
        requestOptions?: TierClient.RequestOptions,
    ): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__deleteTier(request, requestOptions));
    }

    private async __deleteTier(
        request: Brevo.DeleteTierRequest,
        requestOptions?: TierClient.RequestOptions,
    ): Promise<core.WithRawResponse<string>> {
        const { pid, tid } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `loyalty/tier/programs/${core.url.encodePathParam(pid)}/tiers/${core.url.encodePathParam(tid)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Brevo.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Brevo.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Brevo.UnprocessableEntityError(
                        _response.error.body as Brevo.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Brevo.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/loyalty/tier/programs/{pid}/tiers/{tid}",
        );
    }
}
