// This file was auto-generated by Fern from our API Definition.

import type * as Brevo from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             text: "<p>Meeting notes: <b>Action item</b> - visit <a href=\"https://www.brevo.com/\">Brevo</a> for details.</p>"
 *         }
 *     }
 */
export interface PatchCrmNotesIdRequest {
    /** Note ID to update */
    id: string;
    body: Brevo.NoteData;
}
