// This file was auto-generated by Fern from our API Definition.

import type * as Brevo from "../../../../index.js";

/**
 * @example
 *     {
 *         pid: "pid",
 *         contactId: 1,
 *         balanceDefinitionId: "balanceDefinitionId"
 *     }
 */
export interface GetLoyaltyBalanceProgramsPidTransactionHistoryRequest {
    /** Loyalty Program Id */
    pid: string;
    /** Limit the number of records returned */
    limit?: number;
    /** Skip a number of records */
    offset?: number;
    /** Field to sort by */
    sortField?: "createdAt";
    /** Sort order, either asc or desc */
    sort?: Brevo.GetLoyaltyBalanceProgramsPidTransactionHistoryRequestSort;
    /** Contact ID */
    contactId: number;
    /** Balance Definition ID */
    balanceDefinitionId: string;
    /** Filters to apply */
    filters?: string | string[];
}
