// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         pid: "pid",
 *         bdid: "bdid",
 *         name: "name",
 *         unit: "POINTS"
 *     }
 */
export interface UpdateBalanceDefinitionRequest {
    /** Loyalty Program Id */
    pid: string;
    /** Balance Definition Id */
    bdid: string;
    /** Defines when the balance expires within the selected duration. */
    balanceAvailabilityDurationModifier?: UpdateBalanceDefinitionRequest.BalanceAvailabilityDurationModifier;
    /** Unit of time for balance validity. */
    balanceAvailabilityDurationUnit?: UpdateBalanceDefinitionRequest.BalanceAvailabilityDurationUnit;
    /** Number of time units before the balance expires. */
    balanceAvailabilityDurationValue?: number;
    /** Expiration date (`dd/mm` format) or empty if not applicable. */
    balanceExpirationDate?: string;
    /** Defines whether partial credit is allowed when reaching max balance. */
    balanceOptionAmountOvertakingStrategy?: UpdateBalanceDefinitionRequest.BalanceOptionAmountOvertakingStrategy;
    /** Rounding strategy for credit transactions. */
    balanceOptionCreditRounding?: UpdateBalanceDefinitionRequest.BalanceOptionCreditRounding;
    /** Rounding strategy for debit transactions. */
    balanceOptionDebitRounding?: UpdateBalanceDefinitionRequest.BalanceOptionDebitRounding;
    /** Short description of the balance definition. */
    description?: string;
    /** URL of an optional image reference. */
    imageRef?: string;
    /** Maximum allowable balance amount. */
    maxAmount?: number;
    /** Maximum credit allowed per operation. */
    maxCreditAmountLimit?: number;
    /** Maximum debit allowed per operation. */
    maxDebitAmountLimit?: number;
    /** Optional metadata for the balance definition. */
    meta?: Record<string, unknown>;
    /** Minimum allowable balance amount. */
    minAmount?: number;
    /** Name of the balance definition. */
    name: string;
    /** Unit of balance measurement. */
    unit: UpdateBalanceDefinitionRequest.Unit;
}

export namespace UpdateBalanceDefinitionRequest {
    /** Defines when the balance expires within the selected duration. */
    export const BalanceAvailabilityDurationModifier = {
        NoModification: "noModification",
        StartOfPeriod: "startOfPeriod",
        EndOfPeriod: "endOfPeriod",
    } as const;
    export type BalanceAvailabilityDurationModifier =
        (typeof BalanceAvailabilityDurationModifier)[keyof typeof BalanceAvailabilityDurationModifier];
    /** Unit of time for balance validity. */
    export const BalanceAvailabilityDurationUnit = {
        Day: "day",
        Week: "week",
        Month: "month",
        Year: "year",
    } as const;
    export type BalanceAvailabilityDurationUnit =
        (typeof BalanceAvailabilityDurationUnit)[keyof typeof BalanceAvailabilityDurationUnit];
    /** Defines whether partial credit is allowed when reaching max balance. */
    export const BalanceOptionAmountOvertakingStrategy = {
        Strict: "strict",
        Partial: "partial",
    } as const;
    export type BalanceOptionAmountOvertakingStrategy =
        (typeof BalanceOptionAmountOvertakingStrategy)[keyof typeof BalanceOptionAmountOvertakingStrategy];
    /** Rounding strategy for credit transactions. */
    export const BalanceOptionCreditRounding = {
        Lower: "lower",
        Upper: "upper",
        Natural: "natural",
    } as const;
    export type BalanceOptionCreditRounding =
        (typeof BalanceOptionCreditRounding)[keyof typeof BalanceOptionCreditRounding];
    /** Rounding strategy for debit transactions. */
    export const BalanceOptionDebitRounding = {
        Lower: "lower",
        Upper: "upper",
        Natural: "natural",
    } as const;
    export type BalanceOptionDebitRounding =
        (typeof BalanceOptionDebitRounding)[keyof typeof BalanceOptionDebitRounding];
    /** Unit of balance measurement. */
    export const Unit = {
        Points: "POINTS",
        Eur: "EUR",
        Usd: "USD",
        Mxn: "MXN",
        Gbp: "GBP",
        Inr: "INR",
        Cad: "CAD",
        Sgd: "SGD",
        Ron: "RON",
        Jpy: "JPY",
        Myr: "MYR",
        Clp: "CLP",
        Pen: "PEN",
        Mad: "MAD",
        Aud: "AUD",
        Chf: "CHF",
        Brl: "BRL",
    } as const;
    export type Unit = (typeof Unit)[keyof typeof Unit];
}
