// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Brevo from "../../../index.js";

export declare namespace ConversationsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ConversationsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ConversationsClient.Options>;

    constructor(options: ConversationsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * We recommend pinging this endpoint every minute for as long as the agent has to be considered online.
     *
     * @param {Brevo.PostConversationsAgentOnlinePingRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     *
     * @example
     *     await client.conversations.setsAgentsStatusToOnlineFor23Minutes({
     *         agentId: "d9nKoegKSjmCtyK78"
     *     })
     *
     * @example
     *     await client.conversations.setsAgentsStatusToOnlineFor23Minutes({
     *         agentEmail: "liz@getwear.com",
     *         agentName: "Liz",
     *         receivedFrom: "SuperAwesomeHelpdesk"
     *     })
     */
    public setsAgentsStatusToOnlineFor23Minutes(
        request: Brevo.PostConversationsAgentOnlinePingRequest = {},
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(
            this.__setsAgentsStatusToOnlineFor23Minutes(request, requestOptions),
        );
    }

    private async __setsAgentsStatusToOnlineFor23Minutes(
        request: Brevo.PostConversationsAgentOnlinePingRequest = {},
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                "conversations/agentOnlinePing",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/conversations/agentOnlinePing",
        );
    }

    /**
     * @param {Brevo.PostConversationsMessagesRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     *
     * @example
     *     await client.conversations.sendAMessageAsAnAgent({
     *         agentId: "d9nKoegKSjmCtyK78",
     *         text: "Hello! How can I help you?",
     *         visitorId: "kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg"
     *     })
     *
     * @example
     *     await client.conversations.sendAMessageAsAnAgent({
     *         agentEmail: "liz@getwear.com",
     *         agentName: "Liz",
     *         receivedFrom: "SuperAwesomeHelpdesk",
     *         text: "Hello! How can I help you?",
     *         visitorId: "kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg"
     *     })
     *
     * @example
     *     await client.conversations.sendAMessageAsAnAgent({
     *         agentId: "d9nKoegKSjmCtyK78",
     *         receivedFrom: "SuperAwesomeHelpdesk",
     *         text: "Hello! How can I help you?",
     *         visitorId: "kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg"
     *     })
     */
    public sendAMessageAsAnAgent(
        request: Brevo.PostConversationsMessagesRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.ConversationsMessage> {
        return core.HttpResponsePromise.fromPromise(this.__sendAMessageAsAnAgent(request, requestOptions));
    }

    private async __sendAMessageAsAnAgent(
        request: Brevo.PostConversationsMessagesRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.ConversationsMessage>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                "conversations/messages",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.ConversationsMessage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/conversations/messages");
    }

    /**
     * @param {Brevo.GetConversationsMessagesIdRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     * @throws {@link Brevo.NotFoundError}
     *
     * @example
     *     await client.conversations.getAMessage({
     *         id: "id"
     *     })
     */
    public getAMessage(
        request: Brevo.GetConversationsMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.ConversationsMessage> {
        return core.HttpResponsePromise.fromPromise(this.__getAMessage(request, requestOptions));
    }

    private async __getAMessage(
        request: Brevo.GetConversationsMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.ConversationsMessage>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `conversations/messages/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.ConversationsMessage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/conversations/messages/{id}");
    }

    /**
     * Only agents’ messages can be edited.
     *
     * @param {Brevo.PutConversationsMessagesIdRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     * @throws {@link Brevo.NotFoundError}
     *
     * @example
     *     await client.conversations.updateAMessageSentByAnAgent({
     *         id: "id",
     *         text: "Good morning! How can I help you?"
     *     })
     */
    public updateAMessageSentByAnAgent(
        request: Brevo.PutConversationsMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.ConversationsMessage> {
        return core.HttpResponsePromise.fromPromise(this.__updateAMessageSentByAnAgent(request, requestOptions));
    }

    private async __updateAMessageSentByAnAgent(
        request: Brevo.PutConversationsMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.ConversationsMessage>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `conversations/messages/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.ConversationsMessage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/conversations/messages/{id}");
    }

    /**
     * Only agents’ messages can be deleted.
     *
     * @param {Brevo.DeleteConversationsMessagesIdRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     * @throws {@link Brevo.NotFoundError}
     *
     * @example
     *     await client.conversations.deleteAMessageSentByAnAgent({
     *         id: "id"
     *     })
     */
    public deleteAMessageSentByAnAgent(
        request: Brevo.DeleteConversationsMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteAMessageSentByAnAgent(request, requestOptions));
    }

    private async __deleteAMessageSentByAnAgent(
        request: Brevo.DeleteConversationsMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `conversations/messages/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/conversations/messages/{id}",
        );
    }

    /**
     * Example of automated messages: order status, announce new features in your web app, etc.
     *
     * @param {Brevo.PostConversationsPushedMessagesRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     *
     * @example
     *     await client.conversations.sendAnAutomatedMessageToAVisitor({
     *         groupId: "PjRBMhWGen6aRHjif",
     *         text: "Your order has shipped! Here\u2019s your tracking number: 9114 5847 3325 9667 4328 88",
     *         visitorId: "kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg"
     *     })
     *
     * @example
     *     await client.conversations.sendAnAutomatedMessageToAVisitor({
     *         text: "Your order has shipped! Here\u2019s your tracking number: 9114 5847 3325 9667 4328 88",
     *         visitorId: "kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg"
     *     })
     *
     * @example
     *     await client.conversations.sendAnAutomatedMessageToAVisitor({
     *         agentId: "d9nKoegKSjmCtyK78",
     *         text: "Your order has shipped! Here\u2019s your tracking number: 9114 5847 3325 9667 4328 88",
     *         visitorId: "kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg"
     *     })
     */
    public sendAnAutomatedMessageToAVisitor(
        request: Brevo.PostConversationsPushedMessagesRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.ConversationsMessage> {
        return core.HttpResponsePromise.fromPromise(this.__sendAnAutomatedMessageToAVisitor(request, requestOptions));
    }

    private async __sendAnAutomatedMessageToAVisitor(
        request: Brevo.PostConversationsPushedMessagesRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.ConversationsMessage>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                "conversations/pushedMessages",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.ConversationsMessage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/conversations/pushedMessages",
        );
    }

    /**
     * @param {Brevo.GetConversationsPushedMessagesIdRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     * @throws {@link Brevo.NotFoundError}
     *
     * @example
     *     await client.conversations.getAnAutomatedMessage({
     *         id: "id"
     *     })
     */
    public getAnAutomatedMessage(
        request: Brevo.GetConversationsPushedMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.ConversationsMessage> {
        return core.HttpResponsePromise.fromPromise(this.__getAnAutomatedMessage(request, requestOptions));
    }

    private async __getAnAutomatedMessage(
        request: Brevo.GetConversationsPushedMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.ConversationsMessage>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `conversations/pushedMessages/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.ConversationsMessage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/conversations/pushedMessages/{id}",
        );
    }

    /**
     * @param {Brevo.PutConversationsPushedMessagesIdRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     * @throws {@link Brevo.NotFoundError}
     *
     * @example
     *     await client.conversations.updateAnAutomatedMessage({
     *         id: "id",
     *         text: "Your order has shipped! Here\u2019s your tracking number: 9114 5847 4668 7775 9233 54"
     *     })
     */
    public updateAnAutomatedMessage(
        request: Brevo.PutConversationsPushedMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.ConversationsMessage> {
        return core.HttpResponsePromise.fromPromise(this.__updateAnAutomatedMessage(request, requestOptions));
    }

    private async __updateAnAutomatedMessage(
        request: Brevo.PutConversationsPushedMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.ConversationsMessage>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `conversations/pushedMessages/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Brevo.ConversationsMessage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/conversations/pushedMessages/{id}",
        );
    }

    /**
     * @param {Brevo.DeleteConversationsPushedMessagesIdRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     * @throws {@link Brevo.NotFoundError}
     *
     * @example
     *     await client.conversations.deleteAnAutomatedMessage({
     *         id: "id"
     *     })
     */
    public deleteAnAutomatedMessage(
        request: Brevo.DeleteConversationsPushedMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteAnAutomatedMessage(request, requestOptions));
    }

    private async __deleteAnAutomatedMessage(
        request: Brevo.DeleteConversationsPushedMessagesIdRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                `conversations/pushedMessages/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/conversations/pushedMessages/{id}",
        );
    }

    /**
     * Assigns a visitor to a specific agent group or removes them from their current group.
     *
     * @param {Brevo.PutConversationsVisitorGroupRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Brevo.BadRequestError}
     * @throws {@link Brevo.NotFoundError}
     *
     * @example
     *     await client.conversations.setVisitorGroupAssignment({
     *         groupId: "PjRBMhWGen6aRHjif"
     *     })
     */
    public setVisitorGroupAssignment(
        request: Brevo.PutConversationsVisitorGroupRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<Brevo.PutConversationsVisitorGroupResponse> {
        return core.HttpResponsePromise.fromPromise(this.__setVisitorGroupAssignment(request, requestOptions));
    }

    private async __setVisitorGroupAssignment(
        request: Brevo.PutConversationsVisitorGroupRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Brevo.PutConversationsVisitorGroupResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoEnvironment.Default,
                "conversations/visitorGroup",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Brevo.PutConversationsVisitorGroupResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Brevo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Brevo.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/conversations/visitorGroup");
    }
}
