// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         listId: 1000000
 *     }
 */
export interface DeleteListRequest {
    /** Id of the list */
    listId: number;
}
