// This file was auto-generated by Fern from our API Definition.

import * as Brevo from "../../src/api/index";
import { BrevoClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ContactsClient", () => {
    test("getContacts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            contacts: [
                {
                    attributes: {},
                    createdAt: "2017-05-01T17:05:03Z",
                    email: "contact1@example.com",
                    emailBlacklisted: true,
                    id: 247,
                    listIds: [43, 58],
                    listUnsubscribed: [1000000],
                    modifiedAt: "2017-05-01T17:05:03Z",
                    smsBlacklisted: true,
                },
                {
                    attributes: {},
                    createdAt: "2017-05-01T17:05:03Z",
                    email: "33058407248@mailin-sms.com",
                    emailBlacklisted: true,
                    id: 245,
                    listIds: [43, 61, 58],
                    listUnsubscribed: [1000000],
                    modifiedAt: "2017-05-01T17:05:03Z",
                    smsBlacklisted: false,
                },
            ],
            count: 3,
        };
        server.mockEndpoint().get("/contacts").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.contacts.getContacts();
        expect(response).toEqual({
            contacts: [
                {
                    attributes: {},
                    createdAt: "2017-05-01T17:05:03Z",
                    email: "contact1@example.com",
                    emailBlacklisted: true,
                    id: 247,
                    listIds: [43, 58],
                    listUnsubscribed: [1000000],
                    modifiedAt: "2017-05-01T17:05:03Z",
                    smsBlacklisted: true,
                },
                {
                    attributes: {},
                    createdAt: "2017-05-01T17:05:03Z",
                    email: "33058407248@mailin-sms.com",
                    emailBlacklisted: true,
                    id: 245,
                    listIds: [43, 61, 58],
                    listUnsubscribed: [1000000],
                    modifiedAt: "2017-05-01T17:05:03Z",
                    smsBlacklisted: false,
                },
            ],
            count: 3,
        });
    });

    test("getContacts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/contacts").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.getContacts();
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("getContacts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server.mockEndpoint().get("/contacts").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.getContacts();
        }).rejects.toThrow(Brevo.TooManyRequestsError);
    });

    test("createContact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { id: 21 };
        server
            .mockEndpoint()
            .post("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.createContact();
        expect(response).toEqual({
            id: 21,
        });
    });

    test("createContact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createContact();
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("createContact (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_parameter", message: "message" };
        server
            .mockEndpoint()
            .post("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(425)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createContact();
        }).rejects.toThrow(Brevo.TooEarlyError);
    });

    test("getAttributes", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            attributes: [
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "normal",
                    enumeration: [{ label: "Women", value: 1 }],
                    multiCategoryOptions: ["USA"],
                    name: "LASTNAME",
                    type: "text",
                },
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "normal",
                    enumeration: [{ label: "Women", value: 1 }],
                    multiCategoryOptions: ["USA"],
                    name: "FIRSTNAME",
                    type: "text",
                },
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "normal",
                    enumeration: [{ label: "Women", value: 1 }],
                    multiCategoryOptions: ["USA"],
                    name: "DOB",
                    type: "date",
                },
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "category",
                    enumeration: [
                        { label: "Men", value: 1 },
                        { label: "Women", value: 2 },
                        { label: "Kid", value: 3 },
                    ],
                    multiCategoryOptions: ["USA"],
                    name: "GENDER",
                    type: "text",
                },
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "normal",
                    enumeration: [{ label: "Women", value: 1 }],
                    multiCategoryOptions: ["USA"],
                    name: "BDO",
                    type: "user",
                },
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "normal",
                    enumeration: [{ label: "Women", value: 1 }],
                    multiCategoryOptions: ["USA", "India", "France"],
                    name: "COUNTRY",
                    type: "multiple-choice",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/contacts/attributes")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.getAttributes();
        expect(response).toEqual({
            attributes: [
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "normal",
                    enumeration: [
                        {
                            label: "Women",
                            value: 1,
                        },
                    ],
                    multiCategoryOptions: ["USA"],
                    name: "LASTNAME",
                    type: "text",
                },
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "normal",
                    enumeration: [
                        {
                            label: "Women",
                            value: 1,
                        },
                    ],
                    multiCategoryOptions: ["USA"],
                    name: "FIRSTNAME",
                    type: "text",
                },
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "normal",
                    enumeration: [
                        {
                            label: "Women",
                            value: 1,
                        },
                    ],
                    multiCategoryOptions: ["USA"],
                    name: "DOB",
                    type: "date",
                },
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "category",
                    enumeration: [
                        {
                            label: "Men",
                            value: 1,
                        },
                        {
                            label: "Women",
                            value: 2,
                        },
                        {
                            label: "Kid",
                            value: 3,
                        },
                    ],
                    multiCategoryOptions: ["USA"],
                    name: "GENDER",
                    type: "text",
                },
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "normal",
                    enumeration: [
                        {
                            label: "Women",
                            value: 1,
                        },
                    ],
                    multiCategoryOptions: ["USA"],
                    name: "BDO",
                    type: "user",
                },
                {
                    calculatedValue: "COUNT[ORDER_ID,ORDER_DATE,==,NOW(-1)]",
                    category: "normal",
                    enumeration: [
                        {
                            label: "Women",
                            value: 1,
                        },
                    ],
                    multiCategoryOptions: ["USA", "India", "France"],
                    name: "COUNTRY",
                    type: "multiple-choice",
                },
            ],
        });
    });

    test("createAttribute (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};

        server
            .mockEndpoint()
            .post("/contacts/attributes/normal/attributeName")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.contacts.createAttribute({
            attributeCategory: "normal",
            attributeName: "attributeName",
        });
        expect(response).toEqual(undefined);
    });

    test("createAttribute (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts/attributes/normal/attributeName")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createAttribute({
                attributeCategory: "normal",
                attributeName: "attributeName",
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("updateAttribute (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};

        server
            .mockEndpoint()
            .put("/contacts/attributes/category/attributeName")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.contacts.updateAttribute({
            attributeCategory: "category",
            attributeName: "attributeName",
        });
        expect(response).toEqual(undefined);
    });

    test("updateAttribute (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/contacts/attributes/category/attributeName")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateAttribute({
                attributeCategory: "category",
                attributeName: "attributeName",
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("updateAttribute (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/contacts/attributes/category/attributeName")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateAttribute({
                attributeCategory: "category",
                attributeName: "attributeName",
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("deleteAttribute (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/contacts/attributes/normal/attributeName").respondWith().statusCode(200).build();

        const response = await client.contacts.deleteAttribute({
            attributeCategory: "normal",
            attributeName: "attributeName",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteAttribute (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/contacts/attributes/normal/attributeName")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteAttribute({
                attributeCategory: "normal",
                attributeName: "attributeName",
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("deleteAttribute (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/contacts/attributes/normal/attributeName")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteAttribute({
                attributeCategory: "normal",
                attributeName: "attributeName",
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("deleteMultiAttributeOptions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/contacts/attributes/multiple-choice/multipleChoiceAttribute/multipleChoiceAttributeOption")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.contacts.deleteMultiAttributeOptions({
            attributeType: "multiple-choice",
            multipleChoiceAttribute: "multipleChoiceAttribute",
            multipleChoiceAttributeOption: "multipleChoiceAttributeOption",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteMultiAttributeOptions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/contacts/attributes/multiple-choice/multipleChoiceAttribute/multipleChoiceAttributeOption")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteMultiAttributeOptions({
                attributeType: "multiple-choice",
                multipleChoiceAttribute: "multipleChoiceAttribute",
                multipleChoiceAttributeOption: "multipleChoiceAttributeOption",
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("deleteMultiAttributeOptions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/contacts/attributes/multiple-choice/multipleChoiceAttribute/multipleChoiceAttributeOption")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteMultiAttributeOptions({
                attributeType: "multiple-choice",
                multipleChoiceAttribute: "multipleChoiceAttribute",
                multipleChoiceAttributeOption: "multipleChoiceAttributeOption",
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("updateBatchContacts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};

        server.mockEndpoint().post("/contacts/batch").jsonBody(rawRequestBody).respondWith().statusCode(200).build();

        const response = await client.contacts.updateBatchContacts();
        expect(response).toEqual(undefined);
    });

    test("updateBatchContacts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateBatchContacts();
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("createDoiContact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            email: "elly@example.com",
            includeListIds: [36],
            redirectionUrl: "http://requestb.in/173lyyx1",
            templateId: 2,
        };

        server
            .mockEndpoint()
            .post("/contacts/doubleOptinConfirmation")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.contacts.createDoiContact({
            email: "elly@example.com",
            includeListIds: [36],
            redirectionUrl: "http://requestb.in/173lyyx1",
            templateId: 2,
        });
        expect(response).toEqual(undefined);
    });

    test("createDoiContact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            email: "email",
            includeListIds: [1000000, 1000000],
            redirectionUrl: "redirectionUrl",
            templateId: 1000000,
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts/doubleOptinConfirmation")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createDoiContact({
                email: "email",
                includeListIds: [1000000, 1000000],
                redirectionUrl: "redirectionUrl",
                templateId: 1000000,
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("requestContactExport (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { customContactFilter: {} };
        const rawResponseBody = { processId: 78 };
        server
            .mockEndpoint()
            .post("/contacts/export")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.requestContactExport({
            customContactFilter: {},
        });
        expect(response).toEqual({
            processId: 78,
        });
    });

    test("requestContactExport (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { customContactFilter: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts/export")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.requestContactExport({
                customContactFilter: {},
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("requestContactExport (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { customContactFilter: {} };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/contacts/export")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.requestContactExport({
                customContactFilter: {},
            });
        }).rejects.toThrow(Brevo.TooManyRequestsError);
    });

    test("getFolders (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            count: 2,
            folders: [
                { id: 42, name: "Ninja_Form", totalBlacklisted: 98, totalSubscribers: 4567, uniqueSubscribers: 4665 },
                { id: 29, name: "Prestashop", totalBlacklisted: 10, totalSubscribers: 6543, uniqueSubscribers: 6553 },
            ],
        };
        server.mockEndpoint().get("/contacts/folders").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.contacts.getFolders();
        expect(response).toEqual({
            count: 2,
            folders: [
                {
                    id: 42,
                    name: "Ninja_Form",
                    totalBlacklisted: 98,
                    totalSubscribers: 4567,
                    uniqueSubscribers: 4665,
                },
                {
                    id: 29,
                    name: "Prestashop",
                    totalBlacklisted: 10,
                    totalSubscribers: 6543,
                    uniqueSubscribers: 6553,
                },
            ],
        });
    });

    test("getFolders (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/contacts/folders").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.getFolders();
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("createFolder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { id: 5 };
        server
            .mockEndpoint()
            .post("/contacts/folders")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.createFolder({});
        expect(response).toEqual({
            id: 5,
        });
    });

    test("createFolder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts/folders")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createFolder({});
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("getFolder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: 1,
            name: "Client_Folder",
            totalBlacklisted: 987,
            totalSubscribers: 16778,
            uniqueSubscribers: 17765,
        };
        server
            .mockEndpoint()
            .get("/contacts/folders/1000000")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.getFolder({
            folderId: 1000000,
        });
        expect(response).toEqual({
            id: 1,
            name: "Client_Folder",
            totalBlacklisted: 987,
            totalSubscribers: 16778,
            uniqueSubscribers: 17765,
        });
    });

    test("getFolder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/folders/1000000")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getFolder({
                folderId: 1000000,
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("getFolder (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/folders/1000000")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getFolder({
                folderId: 1000000,
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("updateFolder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};

        server
            .mockEndpoint()
            .put("/contacts/folders/1000000")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.contacts.updateFolder({
            folderId: 1000000,
            body: {},
        });
        expect(response).toEqual(undefined);
    });

    test("updateFolder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/contacts/folders/1000000")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateFolder({
                folderId: 1000000,
                body: {},
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("updateFolder (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/contacts/folders/1000000")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateFolder({
                folderId: 1000000,
                body: {},
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("deleteFolder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/contacts/folders/1000000").respondWith().statusCode(200).build();

        const response = await client.contacts.deleteFolder({
            folderId: 1000000,
        });
        expect(response).toEqual(undefined);
    });

    test("deleteFolder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/contacts/folders/1000000")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteFolder({
                folderId: 1000000,
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("deleteFolder (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/contacts/folders/1000000")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteFolder({
                folderId: 1000000,
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("getFolderLists (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            count: 3,
            lists: [
                { id: 46, name: "Reactiv", totalBlacklisted: 0, totalSubscribers: 7655, uniqueSubscribers: 7655 },
                { id: 41, name: "NY_Area", totalBlacklisted: 23, totalSubscribers: 3654, uniqueSubscribers: 3677 },
                { id: 22, name: "VIP_Customer", totalBlacklisted: 72, totalSubscribers: 8753, uniqueSubscribers: 8826 },
            ],
        };
        server
            .mockEndpoint()
            .get("/contacts/folders/1000000/lists")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.getFolderLists({
            folderId: 1000000,
        });
        expect(response).toEqual({
            count: 3,
            lists: [
                {
                    id: 46,
                    name: "Reactiv",
                    totalBlacklisted: 0,
                    totalSubscribers: 7655,
                    uniqueSubscribers: 7655,
                },
                {
                    id: 41,
                    name: "NY_Area",
                    totalBlacklisted: 23,
                    totalSubscribers: 3654,
                    uniqueSubscribers: 3677,
                },
                {
                    id: 22,
                    name: "VIP_Customer",
                    totalBlacklisted: 72,
                    totalSubscribers: 8753,
                    uniqueSubscribers: 8826,
                },
            ],
        });
    });

    test("getFolderLists (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/folders/1000000/lists")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getFolderLists({
                folderId: 1000000,
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("getFolderLists (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/folders/1000000/lists")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getFolderLists({
                folderId: 1000000,
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("importContacts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { processId: 78 };
        server
            .mockEndpoint()
            .post("/contacts/import")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.importContacts();
        expect(response).toEqual({
            processId: 78,
        });
    });

    test("importContacts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts/import")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.importContacts();
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("getLists (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            count: 2,
            lists: [
                {
                    id: 53,
                    name: "Spanish_Speakers",
                    totalBlacklisted: 65,
                    totalSubscribers: 5432,
                    uniqueSubscribers: 5497,
                    folderId: 1,
                },
                {
                    id: 50,
                    name: "Other",
                    totalBlacklisted: 765,
                    totalSubscribers: 10976,
                    uniqueSubscribers: 11741,
                    folderId: 2,
                },
            ],
        };
        server.mockEndpoint().get("/contacts/lists").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.contacts.getLists();
        expect(response).toEqual({
            count: 2,
            lists: [
                {
                    id: 53,
                    name: "Spanish_Speakers",
                    totalBlacklisted: 65,
                    totalSubscribers: 5432,
                    uniqueSubscribers: 5497,
                    folderId: 1,
                },
                {
                    id: 50,
                    name: "Other",
                    totalBlacklisted: 765,
                    totalSubscribers: 10976,
                    uniqueSubscribers: 11741,
                    folderId: 2,
                },
            ],
        });
    });

    test("getLists (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/contacts/lists").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.getLists();
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("createList (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { folderId: 2, name: "Magento Customer - ES" };
        const rawResponseBody = { id: 5 };
        server
            .mockEndpoint()
            .post("/contacts/lists")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.createList({
            folderId: 2,
            name: "Magento Customer - ES",
        });
        expect(response).toEqual({
            id: 5,
        });
    });

    test("createList (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { folderId: 1000000, name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts/lists")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createList({
                folderId: 1000000,
                name: "name",
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("getList (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: 12,
            name: "Newsletter_Weekly",
            totalBlacklisted: 63,
            totalSubscribers: 6533,
            uniqueSubscribers: 6596,
            campaignStats: [
                {
                    campaignId: 15,
                    stats: {
                        appleMppOpens: 10,
                        clickers: 789,
                        complaints: 0,
                        deferred: 0,
                        delivered: 6632,
                        estimatedViews: 560,
                        hardBounces: 4,
                        listId: 2,
                        opensRate: 29.54,
                        returnBounce: 5,
                        sent: 6645,
                        softBounces: 34,
                        trackableViews: 5661,
                        trackableViewsRate: 23.45,
                        uniqueClicks: 701,
                        uniqueViews: 3442,
                        unsubscriptions: 4,
                        viewed: 4322,
                    },
                },
                {
                    campaignId: 45,
                    stats: {
                        appleMppOpens: 10,
                        clickers: 788,
                        complaints: 1,
                        deferred: 0,
                        delivered: 4078,
                        estimatedViews: 560,
                        hardBounces: 2,
                        listId: 2,
                        opensRate: 29.54,
                        returnBounce: 5,
                        sent: 4334,
                        softBounces: 18,
                        trackableViews: 5661,
                        trackableViewsRate: 23.45,
                        uniqueClicks: 654,
                        uniqueViews: 987,
                        unsubscriptions: 4,
                        viewed: 1555,
                    },
                },
            ],
            createdAt: "2016-02-26T11:56:08Z",
            dynamicList: false,
            folderId: 1,
        };
        server
            .mockEndpoint()
            .get("/contacts/lists/1000000")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.getList({
            listId: 1000000,
        });
        expect(response).toEqual({
            id: 12,
            name: "Newsletter_Weekly",
            totalBlacklisted: 63,
            totalSubscribers: 6533,
            uniqueSubscribers: 6596,
            campaignStats: [
                {
                    campaignId: 15,
                    stats: {
                        appleMppOpens: 10,
                        clickers: 789,
                        complaints: 0,
                        deferred: 0,
                        delivered: 6632,
                        estimatedViews: 560,
                        hardBounces: 4,
                        listId: 2,
                        opensRate: 29.54,
                        returnBounce: 5,
                        sent: 6645,
                        softBounces: 34,
                        trackableViews: 5661,
                        trackableViewsRate: 23.45,
                        uniqueClicks: 701,
                        uniqueViews: 3442,
                        unsubscriptions: 4,
                        viewed: 4322,
                    },
                },
                {
                    campaignId: 45,
                    stats: {
                        appleMppOpens: 10,
                        clickers: 788,
                        complaints: 1,
                        deferred: 0,
                        delivered: 4078,
                        estimatedViews: 560,
                        hardBounces: 2,
                        listId: 2,
                        opensRate: 29.54,
                        returnBounce: 5,
                        sent: 4334,
                        softBounces: 18,
                        trackableViews: 5661,
                        trackableViewsRate: 23.45,
                        uniqueClicks: 654,
                        uniqueViews: 987,
                        unsubscriptions: 4,
                        viewed: 1555,
                    },
                },
            ],
            createdAt: "2016-02-26T11:56:08Z",
            dynamicList: false,
            folderId: 1,
        });
    });

    test("getList (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/lists/1000000")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getList({
                listId: 1000000,
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("getList (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/lists/1000000")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getList({
                listId: 1000000,
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("updateList (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};

        server
            .mockEndpoint()
            .put("/contacts/lists/1000000")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.contacts.updateList({
            listId: 1000000,
        });
        expect(response).toEqual(undefined);
    });

    test("updateList (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/contacts/lists/1000000")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateList({
                listId: 1000000,
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("updateList (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/contacts/lists/1000000")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateList({
                listId: 1000000,
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("deleteList (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/contacts/lists/1000000").respondWith().statusCode(200).build();

        const response = await client.contacts.deleteList({
            listId: 1000000,
        });
        expect(response).toEqual(undefined);
    });

    test("deleteList (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/contacts/lists/1000000")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteList({
                listId: 1000000,
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("deleteList (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/contacts/lists/1000000")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteList({
                listId: 1000000,
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("getContactsFromList (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            contacts: [
                {
                    attributes: {},
                    createdAt: "2017-05-12T12:30:00Z",
                    email: "alex.pain@example.com",
                    emailBlacklisted: false,
                    id: 45,
                    listIds: [12, 9, 20],
                    listUnsubscribed: [1, 2],
                    modifiedAt: "2017-05-12T12:30:00Z",
                    smsBlacklisted: true,
                },
                {
                    attributes: {},
                    createdAt: "2017-05-12T12:30:00Z",
                    email: "john.smith@example.com",
                    emailBlacklisted: true,
                    id: 32,
                    listIds: [12],
                    listUnsubscribed: [1],
                    modifiedAt: "2017-05-12T12:30:00Z",
                    smsBlacklisted: false,
                },
                {
                    attributes: {},
                    createdAt: "2017-05-12T12:30:00Z",
                    email: "helen.rose@example.com",
                    emailBlacklisted: true,
                    id: 65,
                    listIds: [12, 9, 20],
                    listUnsubscribed: [1],
                    modifiedAt: "2017-05-12T12:30:00Z",
                    smsBlacklisted: false,
                },
            ],
            count: 17655,
        };
        server
            .mockEndpoint()
            .get("/contacts/lists/1000000/contacts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.getContactsFromList({
            listId: 1000000,
        });
        expect(response).toEqual({
            contacts: [
                {
                    attributes: {},
                    createdAt: "2017-05-12T12:30:00Z",
                    email: "alex.pain@example.com",
                    emailBlacklisted: false,
                    id: 45,
                    listIds: [12, 9, 20],
                    listUnsubscribed: [1, 2],
                    modifiedAt: "2017-05-12T12:30:00Z",
                    smsBlacklisted: true,
                },
                {
                    attributes: {},
                    createdAt: "2017-05-12T12:30:00Z",
                    email: "john.smith@example.com",
                    emailBlacklisted: true,
                    id: 32,
                    listIds: [12],
                    listUnsubscribed: [1],
                    modifiedAt: "2017-05-12T12:30:00Z",
                    smsBlacklisted: false,
                },
                {
                    attributes: {},
                    createdAt: "2017-05-12T12:30:00Z",
                    email: "helen.rose@example.com",
                    emailBlacklisted: true,
                    id: 65,
                    listIds: [12, 9, 20],
                    listUnsubscribed: [1],
                    modifiedAt: "2017-05-12T12:30:00Z",
                    smsBlacklisted: false,
                },
            ],
            count: 17655,
        });
    });

    test("getContactsFromList (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/lists/1000000/contacts")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactsFromList({
                listId: 1000000,
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("getContactsFromList (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/lists/1000000/contacts")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactsFromList({
                listId: 1000000,
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("addContactToList (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { emails: ["jeff32@example.com", "jim56@example.com"] };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/add")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.addContactToList({
            listId: 1000000,
            body: {
                emails: ["jeff32@example.com", "jim56@example.com"],
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("addContactToList (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { extIds: ["ext234", "ext456"] };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/add")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.addContactToList({
            listId: 1000000,
            body: {
                extIds: ["ext234", "ext456"],
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("addContactToList (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: [1, 2] };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/add")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.addContactToList({
            listId: 1000000,
            body: {
                ids: [1, 2],
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("addContactToList (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { emails: ["jeff32@example.com", "jim56@example.com"] };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/add")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.addContactToList({
            listId: 1000000,
            body: {
                emails: ["jeff32@example.com", "jim56@example.com"],
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("addContactToList (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { emails: ["jeff32@example.com", "jim56@example.com"] };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/add")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.addContactToList({
            listId: 1000000,
            body: {
                emails: ["jeff32@example.com", "jim56@example.com"],
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("addContactToList (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { emails: ["jeff32@example.com", "jim56@example.com"] };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/add")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.addContactToList({
            listId: 1000000,
            body: {
                emails: ["jeff32@example.com", "jim56@example.com"],
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("addContactToList (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/add")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.addContactToList({
                listId: 1000000,
                body: {},
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("addContactToList (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/add")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.addContactToList({
                listId: 1000000,
                body: {},
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("removeContactFromList (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { all: true };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.removeContactFromList({
            listId: 1000000,
            body: {
                all: true,
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("removeContactFromList (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { emails: ["jeff32@example.com", "jim56@example.com"] };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.removeContactFromList({
            listId: 1000000,
            body: {
                emails: ["jeff32@example.com", "jim56@example.com"],
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("removeContactFromList (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { extIds: ["ext234", "ext456"] };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.removeContactFromList({
            listId: 1000000,
            body: {
                extIds: ["ext234", "ext456"],
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("removeContactFromList (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: [1, 2] };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.removeContactFromList({
            listId: 1000000,
            body: {
                ids: [1, 2],
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("removeContactFromList (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { all: true };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.removeContactFromList({
            listId: 1000000,
            body: {
                all: true,
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("removeContactFromList (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { all: true };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.removeContactFromList({
            listId: 1000000,
            body: {
                all: true,
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("removeContactFromList (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { all: true };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.removeContactFromList({
            listId: 1000000,
            body: {
                all: true,
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("removeContactFromList (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { all: true };
        const rawResponseBody = {
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.removeContactFromList({
            listId: 1000000,
            body: {
                all: true,
            },
        });
        expect(response).toEqual({
            contacts: {
                failure: ["jeff32@example.com, jim56@example.com"],
                processId: 78,
                success: ["success"],
                total: 27,
            },
        });
    });

    test("removeContactFromList (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.removeContactFromList({
                listId: 1000000,
                body: {},
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("removeContactFromList (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts/lists/1000000/contacts/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.removeContactFromList({
                listId: 1000000,
                body: {},
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("getSegments (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            count: 2,
            segments: [
                { categoryName: "Name1", id: 53, segmentName: "Segment1", updatedAt: "2017-03-12T12:30:00Z" },
                { categoryName: "Name2", id: 50, segmentName: "Segment2", updatedAt: "2017-03-12T12:30:00Z" },
            ],
        };
        server.mockEndpoint().get("/contacts/segments").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.contacts.getSegments();
        expect(response).toEqual({
            count: 2,
            segments: [
                {
                    categoryName: "Name1",
                    id: 53,
                    segmentName: "Segment1",
                    updatedAt: "2017-03-12T12:30:00Z",
                },
                {
                    categoryName: "Name2",
                    id: 50,
                    segmentName: "Segment2",
                    updatedAt: "2017-03-12T12:30:00Z",
                },
            ],
        });
    });

    test("getSegments (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/contacts/segments").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.getSegments();
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("getContactInfo (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            attributes: {},
            createdAt: "2017-05-02T16:40:31Z",
            email: "peggy.rain@example.com",
            emailBlacklisted: false,
            id: 42,
            listIds: [40],
            listUnsubscribed: [1000000],
            modifiedAt: "2017-05-02T16:40:31Z",
            smsBlacklisted: false,
            statistics: {
                clicked: [
                    {
                        campaignId: 21,
                        links: [
                            {
                                count: 2,
                                eventTime: "2016-05-03T21:25:01Z",
                                ip: "66.249.93.118",
                                url: "https://url.domain.com/fbe5387ec717e333628380454f68670010b205ff/1/go?uid={EMAIL}&utm_source=brevo&utm_campaign=test_camp&utm_medium=email",
                            },
                        ],
                    },
                ],
                complaints: [{ campaignId: 3, eventTime: "2017-03-12T20:15:13Z" }],
                delivered: [{ campaignId: 21, eventTime: "2016-05-03T21:24:56Z" }],
                hardBounces: [{ campaignId: 3, eventTime: "2017-03-12T20:15:13Z" }],
                messagesSent: [
                    { campaignId: 21, eventTime: "2016-05-03T20:15:13Z" },
                    { campaignId: 42, eventTime: "2016-10-17T10:30:01Z" },
                ],
                opened: [
                    { campaignId: 21, count: 2, eventTime: "2016-05-03T21:24:56Z", ip: "66.249.93.118" },
                    { campaignId: 68, count: 1, eventTime: "2017-01-30T13:56:40Z", ip: "66.249.93.217" },
                ],
                softBounces: [{ campaignId: 3, eventTime: "2017-03-12T20:15:13Z" }],
                transacAttributes: [{}],
                unsubscriptions: {
                    adminUnsubscription: [{ eventTime: "2017-03-12T20:15:13Z", ip: "165.87.3.15" }],
                    userUnsubscription: [{ campaignId: 3, eventTime: "2017-03-12T20:15:13Z", ip: "165.87.3.15" }],
                },
            },
        };
        server
            .mockEndpoint()
            .get("/contacts/identifier")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.getContactInfo({
            identifier: "identifier",
        });
        expect(response).toEqual({
            attributes: {},
            createdAt: "2017-05-02T16:40:31Z",
            email: "peggy.rain@example.com",
            emailBlacklisted: false,
            id: 42,
            listIds: [40],
            listUnsubscribed: [1000000],
            modifiedAt: "2017-05-02T16:40:31Z",
            smsBlacklisted: false,
            statistics: {
                clicked: [
                    {
                        campaignId: 21,
                        links: [
                            {
                                count: 2,
                                eventTime: "2016-05-03T21:25:01Z",
                                ip: "66.249.93.118",
                                url: "https://url.domain.com/fbe5387ec717e333628380454f68670010b205ff/1/go?uid={EMAIL}&utm_source=brevo&utm_campaign=test_camp&utm_medium=email",
                            },
                        ],
                    },
                ],
                complaints: [
                    {
                        campaignId: 3,
                        eventTime: "2017-03-12T20:15:13Z",
                    },
                ],
                delivered: [
                    {
                        campaignId: 21,
                        eventTime: "2016-05-03T21:24:56Z",
                    },
                ],
                hardBounces: [
                    {
                        campaignId: 3,
                        eventTime: "2017-03-12T20:15:13Z",
                    },
                ],
                messagesSent: [
                    {
                        campaignId: 21,
                        eventTime: "2016-05-03T20:15:13Z",
                    },
                    {
                        campaignId: 42,
                        eventTime: "2016-10-17T10:30:01Z",
                    },
                ],
                opened: [
                    {
                        campaignId: 21,
                        count: 2,
                        eventTime: "2016-05-03T21:24:56Z",
                        ip: "66.249.93.118",
                    },
                    {
                        campaignId: 68,
                        count: 1,
                        eventTime: "2017-01-30T13:56:40Z",
                        ip: "66.249.93.217",
                    },
                ],
                softBounces: [
                    {
                        campaignId: 3,
                        eventTime: "2017-03-12T20:15:13Z",
                    },
                ],
                transacAttributes: [{}],
                unsubscriptions: {
                    adminUnsubscription: [
                        {
                            eventTime: "2017-03-12T20:15:13Z",
                            ip: "165.87.3.15",
                        },
                    ],
                    userUnsubscription: [
                        {
                            campaignId: 3,
                            eventTime: "2017-03-12T20:15:13Z",
                            ip: "165.87.3.15",
                        },
                    ],
                },
            },
        });
    });

    test("getContactInfo (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/identifier")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactInfo({
                identifier: "identifier",
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("getContactInfo (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/identifier")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactInfo({
                identifier: "identifier",
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("updateContact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};

        server
            .mockEndpoint()
            .put("/contacts/identifier")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.contacts.updateContact({
            identifier: "identifier",
        });
        expect(response).toEqual(undefined);
    });

    test("updateContact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/contacts/identifier")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContact({
                identifier: "identifier",
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("updateContact (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/contacts/identifier")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContact({
                identifier: "identifier",
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("updateContact (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_parameter", message: "message" };
        server
            .mockEndpoint()
            .put("/contacts/identifier")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(425)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContact({
                identifier: "identifier",
            });
        }).rejects.toThrow(Brevo.TooEarlyError);
    });

    test("deleteContact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/contacts/identifier").respondWith().statusCode(200).build();

        const response = await client.contacts.deleteContact({
            identifier: "identifier",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteContact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/contacts/identifier")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteContact({
                identifier: "identifier",
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("deleteContact (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/contacts/identifier")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteContact({
                identifier: "identifier",
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });

    test("deleteContact (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .delete("/contacts/identifier")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteContact({
                identifier: "identifier",
            });
        }).rejects.toThrow(Brevo.MethodNotAllowedError);
    });

    test("getContactStats (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            clicked: [
                {
                    campaignId: 21,
                    links: [
                        {
                            count: 2,
                            eventTime: "2016-05-03T21:25:01Z",
                            ip: "66.249.93.118",
                            url: "https://url.domain.com/fbe5387ec717e333628380454f68670010b205ff/1/go?uid={EMAIL}&utm_source=brevo&utm_campaign=test_camp&utm_medium=email",
                        },
                    ],
                },
            ],
            complaints: [{ campaignId: 3, eventTime: "2017-03-12T20:15:13Z" }],
            delivered: [{ campaignId: 21, eventTime: "2016-05-03T21:24:56Z" }],
            hardBounces: [{ campaignId: 3, eventTime: "2017-03-12T20:15:13Z" }],
            messagesSent: [
                { campaignId: 21, eventTime: "2016-05-03T20:15:13Z" },
                { campaignId: 42, eventTime: "2016-10-17T10:30:01Z" },
                { campaignId: 45, eventTime: "2016-11-09T11:45:02Z" },
            ],
            opened: [
                { campaignId: 21, count: 2, eventTime: "2016-05-03T21:24:56Z", ip: "66.249.93.118" },
                { campaignId: 45, count: 1, eventTime: "2017-01-30T13:56:40Z", ip: "66.249.93.217" },
            ],
            softBounces: [{ campaignId: 3, eventTime: "2017-03-12T20:15:13Z" }],
            transacAttributes: [{ orderDate: "2017-03-12", orderId: 248, orderPrice: 24.99 }],
            unsubscriptions: {
                adminUnsubscription: [{ eventTime: "2017-03-12T20:15:13Z", ip: "165.87.3.15" }],
                userUnsubscription: [{ campaignId: 3, eventTime: "2017-03-12T20:15:13Z", ip: "165.87.3.15" }],
            },
        };
        server
            .mockEndpoint()
            .get("/contacts/identifier/campaignStats")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.getContactStats({
            identifier: "identifier",
        });
        expect(response).toEqual({
            clicked: [
                {
                    campaignId: 21,
                    links: [
                        {
                            count: 2,
                            eventTime: "2016-05-03T21:25:01Z",
                            ip: "66.249.93.118",
                            url: "https://url.domain.com/fbe5387ec717e333628380454f68670010b205ff/1/go?uid={EMAIL}&utm_source=brevo&utm_campaign=test_camp&utm_medium=email",
                        },
                    ],
                },
            ],
            complaints: [
                {
                    campaignId: 3,
                    eventTime: "2017-03-12T20:15:13Z",
                },
            ],
            delivered: [
                {
                    campaignId: 21,
                    eventTime: "2016-05-03T21:24:56Z",
                },
            ],
            hardBounces: [
                {
                    campaignId: 3,
                    eventTime: "2017-03-12T20:15:13Z",
                },
            ],
            messagesSent: [
                {
                    campaignId: 21,
                    eventTime: "2016-05-03T20:15:13Z",
                },
                {
                    campaignId: 42,
                    eventTime: "2016-10-17T10:30:01Z",
                },
                {
                    campaignId: 45,
                    eventTime: "2016-11-09T11:45:02Z",
                },
            ],
            opened: [
                {
                    campaignId: 21,
                    count: 2,
                    eventTime: "2016-05-03T21:24:56Z",
                    ip: "66.249.93.118",
                },
                {
                    campaignId: 45,
                    count: 1,
                    eventTime: "2017-01-30T13:56:40Z",
                    ip: "66.249.93.217",
                },
            ],
            softBounces: [
                {
                    campaignId: 3,
                    eventTime: "2017-03-12T20:15:13Z",
                },
            ],
            transacAttributes: [
                {
                    orderDate: "2017-03-12",
                    orderId: 248,
                    orderPrice: 24.99,
                },
            ],
            unsubscriptions: {
                adminUnsubscription: [
                    {
                        eventTime: "2017-03-12T20:15:13Z",
                        ip: "165.87.3.15",
                    },
                ],
                userUnsubscription: [
                    {
                        campaignId: 3,
                        eventTime: "2017-03-12T20:15:13Z",
                        ip: "165.87.3.15",
                    },
                ],
            },
        });
    });

    test("getContactStats (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/identifier/campaignStats")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactStats({
                identifier: "identifier",
            });
        }).rejects.toThrow(Brevo.BadRequestError);
    });

    test("getContactStats (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/contacts/identifier/campaignStats")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactStats({
                identifier: "identifier",
            });
        }).rejects.toThrow(Brevo.NotFoundError);
    });
});
