// This file was auto-generated by Fern from our API Definition.

export interface CreateBatchOrderResponse {
    /** Batch ID of the request */
    batchId: number;
    /** Number of orders */
    count?: number | undefined;
}
