// This file was auto-generated by Fern from our API Definition.

export interface CreateUpdateCategoryResponse {
    /** ID of the category when a new category is created */
    id?: number | undefined;
}
