/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Brevo);
  }
}(this, function(expect, Brevo) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Brevo.TransactionalWhatsAppApi();
  });

  describe('(package)', function() {
    describe('TransactionalWhatsAppApi', function() {
      describe('getWhatsappEventReport', function() {
        it('should call getWhatsappEventReport successfully', function(done) {
          // TODO: uncomment, update parameter values for getWhatsappEventReport call and complete the assertions
          /*
          var opts = {};
          opts.limit = 2500;
          opts.offset = 0;
          opts.startDate = "startDate_example";
          opts.endDate = "endDate_example";
          opts.days = 789;
          opts.contactNumber = "contactNumber_example";
          opts.event = "event_example";
          opts.sort = "desc";

          instance.getWhatsappEventReport(opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Brevo.GetWhatsappEventReport);
            {
              let dataCtr = data.events;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Brevo.GetWhatsappEventReportEvents);
                expect(data.contactNumber).to.be.a('string');
                expect(data.contactNumber).to.be("919876543210");
                expect(data._date).to.be.a('string');
                expect(data._date).to.be("2017-03-12T12:30:00Z");
                expect(data.messageId).to.be.a('string');
                expect(data.messageId).to.be("23befbae-1505-47a8-bd27-e30ef739f32c");
                expect(data.event).to.be.a('string');
                expect(data.event).to.be("delivered");
                expect(data.reason).to.be.a('string');
                expect(data.reason).to.be("23befbae-1505-47a8-bd27-e30ef739f32c");
                expect(data.body).to.be.a('string');
                expect(data.body).to.be("Hi! I am a reply");
                expect(data.mediaUrl).to.be.a('string');
                expect(data.mediaUrl).to.be("https://example.com/media.png");
                expect(data.senderNumber).to.be.a('string');
                expect(data.senderNumber).to.be("919876543210");

                      }
            }

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('sendWhatsappMessage', function() {
        it('should call sendWhatsappMessage successfully', function(done) {
          // TODO: uncomment, update parameter values for sendWhatsappMessage call and complete the assertions
          /*
          var sendWhatsappMessage = new Brevo.SendWhatsappMessage();
          sendWhatsappMessage.templateId = 123;
          sendWhatsappMessage.text = "Hi! There i am a message";
          sendWhatsappMessage.senderNumber = "919876543210";
          sendWhatsappMessage.contactNumbers = ["919876543210"];

          instance.sendWhatsappMessage(sendWhatsappMessage).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Brevo.InlineResponse2013);
            expect(data.messageId).to.be.a('string');
            expect(data.messageId).to.be("23befbae-1505-47a8-bd27-e30ef739f32c");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
