// This file was auto-generated by Fern from our API Definition.

export interface GetSmsTemplatesResponse {
    /** Count of transactional sms templates */
    count?: number;
    templates?: GetSmsTemplatesResponse.Templates.Item[];
}

export namespace GetSmsTemplatesResponse {
    export type Templates = Templates.Item[];

    export namespace Templates {
        export interface Item {
            /** ID of the template */
            id?: number;
            /** Name of the template */
            name?: string;
            /** URL shortening is enabled */
            short_url_enabled?: boolean;
            /** message content for the sms */
            message?: string;
            /** Manage US compliance */
            compliance?: Item.Compliance;
            /** Enable Unicode encryption. */
            encryption?: boolean;
            /** Support unicode characters in the sms. */
            unicode_sms?: boolean;
            /** file name of the media. */
            media_file?: string;
            /** file size in bytes. */
            media_file_size?: string;
            /** URL of the image. */
            media_url?: string;
            /** Creation UTC date-time of the template (YYYY-MM-DDTHH:mm:ss.SSSZ) */
            createdAt?: string;
            /** Creation UTC date-time of the template (YYYY-MM-DDTHH:mm:ss.SSSZ) */
            updatedAt?: string;
        }

        export namespace Item {
            /**
             * Manage US compliance
             */
            export interface Compliance {
                /** US compliance is enabled. */
                compliance_toggle?: boolean;
                /** A recognizable prefix will ensure your audience knows who you are. Recommended by the U.S. carriers. */
                organisation_prefix?: string;
                /** Instructions to unsubscribe from future communications. Must include STOP keyword. */
                stop_keyword?: string;
            }
        }
    }
}
