// This file was auto-generated by Fern from our API Definition.

export interface GetSendersResponse {
    /** List of the senders available in your account */
    senders?: GetSendersResponse.Senders.Item[] | undefined;
}

export namespace GetSendersResponse {
    export type Senders = Senders.Item[];

    export namespace Senders {
        export interface Item {
            /** Status of sender (true=activated, false=deactivated) */
            active: boolean;
            /** From Email associated to the sender */
            email: string;
            /** Id of the sender */
            id: number;
            /**
             * List of dedicated IP(s) available in the account. This
             * data is displayed only for dedicated IPs. For standard accounts,
             * this will be an empty array.
             */
            ips: Item.Ips.Item[];
            /** From Name associated to the sender */
            name: string;
        }

        export namespace Item {
            export type Ips = Ips.Item[];

            export namespace Ips {
                export interface Item {
                    /** Domain of the IP */
                    domain: string;
                    /** Dedicated IP available in your account */
                    ip: string;
                    /** Weight of the IP for this sender */
                    weight: number;
                }
            }
        }
    }
}
