// This file was auto-generated by Fern from our API Definition.

export interface GetSmsEventsResponse {
    events?: GetSmsEventsResponse.Events.Item[] | undefined;
}

export namespace GetSmsEventsResponse {
    export type Events = Events.Item[];

    export namespace Events {
        export interface Item {
            /** UTC date-time on which the event has been generated */
            date?: string | undefined;
            /** Event which occurred */
            event?: Item.Event | undefined;
            /** Message ID which generated the event */
            messageId?: string | undefined;
            /** Phone number which has generated the event */
            phoneNumber?: string | undefined;
            /** Reason of bounce (only available if the event is hardbounce or softbounce) */
            reason?: string | undefined;
            reply?: string | undefined;
            /** Tag of the SMS which generated the event */
            tag?: string | undefined;
        }

        export namespace Item {
            /** Event which occurred */
            export const Event = {
                Bounces: "bounces",
                HardBounces: "hardBounces",
                SoftBounces: "softBounces",
                Delivered: "delivered",
                Sent: "sent",
                Accepted: "accepted",
                Unsubscription: "unsubscription",
                Replies: "replies",
                Blocked: "blocked",
                Rejected: "rejected",
                Skipped: "skipped",
            } as const;
            export type Event = (typeof Event)[keyof typeof Event];
        }
    }
}
