// This file was auto-generated by Fern from our API Definition.

export const GetSmsEventsRequestEvent = {
    Bounces: "bounces",
    HardBounces: "hardBounces",
    SoftBounces: "softBounces",
    Delivered: "delivered",
    Sent: "sent",
    Accepted: "accepted",
    Unsubscription: "unsubscription",
    Replies: "replies",
    Blocked: "blocked",
    Rejected: "rejected",
    Skipped: "skipped",
} as const;
export type GetSmsEventsRequestEvent = (typeof GetSmsEventsRequestEvent)[keyof typeof GetSmsEventsRequestEvent];
