// This file was auto-generated by Fern from our API Definition.

export interface GetTransacAggregatedSmsReportResponse {
    /** Number of accepted SMS for the timeframe */
    accepted?: number | undefined;
    /** Number of blocked contact for the timeframe */
    blocked?: number | undefined;
    /** Number of delivered SMS for the timeframe */
    delivered?: number | undefined;
    /** Number of hardbounces for the timeframe */
    hardBounces?: number | undefined;
    /** Time frame of the report */
    range?: string | undefined;
    /** Number of rejected SMS for the timeframe */
    rejected?: number | undefined;
    /** Number of answered SMS for the timeframe */
    replied?: number | undefined;
    /** Number of requests for the timeframe */
    requests?: number | undefined;
    /** Number of skipped SMS for the timeframe */
    skipped?: number | undefined;
    /** Number of softbounces for the timeframe */
    softBounces?: number | undefined;
    /** Number of unsubscription for the timeframe */
    unsubscribed?: number | undefined;
}
